### ISSUE TITLE
More verification

### ISSUE THREAD

**Issue by VanessaQi** [AguaClara/humic_acid#14]
1 If a mathematical model could be set up from previous task, the team will conduct more tests for different HA concentrations to verify the validity of the model.

2 Schedule a meeting with Monroe to consult the future investigation.

**Comment by SambaSowe** [comment]
Also if we end up having spare time, we should test other potential affects on Humic Acid removal such as temperature of the water, etc.

**Comment by VanessaQi** [comment]
will continue Fall 2018 semester
