### ISSUE TITLE
No floc formation when expected

### ISSUE THREAD

**Issue by pjm326** [AguaClara/humic_acid#17]
There was no floc blanket formation at 5mg/L HA and 0.3mg/L Coag, even though one formed last semester under these same conditions

![img_3796](https://user-images.githubusercontent.com/36024667/36938132-426db4a2-1eeb-11e8-86aa-d90577b079da.jpeg)

**Comment by VanessaQi** [comment]
We consulted with Monroe and he said because the coag concentration is low (lower than reasonable lower bound--0.5mg/L), it's possible to not have a floc blanket.
