### ISSUE TITLE
Affluent turbidity drops severely then gradually rises over the course of the experiment

### ISSUE THREAD

**Issue by pjm326** [AguaClara/humic_acid#18]
for the 0.3 and 0.5mg/L coag experiment, the affluent turbidity would never reach a steady state

**Comment by pjm326** [comment]
Added pressure sensor to monitor head loss across the flocculator to tell us if the rising turbidity was due to coagulant sticking to the walls of the flocculator tubing

**Comment by VanessaQi** [comment]
We observed that the pressure difference increased the the experiment ran longer ---greater head loss
