### ISSUE TITLE
Effluent Turbidity jumps fast after it reaches steady state---a camera may be needed

### ISSUE THREAD

**Issue by VanessaQi** [AguaClara/humic_acid#22]
Hi @monroews , for our last experiment, the effluent turbidity jumps very fast after it reaches the steady state and we are not sure if its because our stock ran out or other reasons (based on our calculation, the stock solution should be enough). We may need a camera to record what happened during that time and also check when does the floc blanket start form.

**Comment by monroews** [comment]
Camera is ordered and will arrive tomorrow.
Ideally post the graph showing the data that you want to discuss. 
You can discuss with some of the other teams how they installed their camera. You may need an RA or team lead with permissions to install software.
