### ISSUE TITLE
Larger bucket needed for coag stock

### ISSUE THREAD

**Issue by VanessaQi** [AguaClara/humic_acid#24]
Hey @monroews by using the camera, we realize the experiment runs longer than we thought so we need a large bucket right now to put more coag solution. Do we still have this bucket at lab?

**Comment by monroews** [comment]
Is there any reason why you don't increase the coagulant stock concentration? That is the simplest way to increase the experimental run time. I assume the coagulant pump is operating at more than 5 rpm.

**Comment by VanessaQi** [comment]
yes so if we increase concentration more, the pump speed will be very close to 5 rpm.

**Comment by monroews** [comment]
You could switch to the smaller pump tubing size. I think Fluoride has made this change.
