### ISSUE TITLE
Coagulant Issues

### ISSUE THREAD

**Issue by SambaSowe** [AguaClara/humic_acid#26]
Our coagulant container was running out of coagulant too early into the experiment so the turbidity was not at the lowest it could drop to. We changed the dilution factor and have access to a larger coagulant bottle which we will use.

The coagulant did not pump in our experiment where we redid the 10 mg/L HA with .5 mg/L coagulant. We believe this is due to the microtubing being clogged, so we cut the clogged portion. We are running our third attempt at this coagulant concentration to test if the coagulant pumps properly.

**Comment by VanessaQi** [comment]
The problem is saved as what's stated above!
