### ISSUE TITLE
Spectrophotometer Test-Humic Acid +Water (Sep.17-Oct.1)

### ISSUE THREAD

**Issue by VanessaQi** [AguaClara/humic_acid#27]
Use spectrophotometer to investigate the humic acid concentration in tap water and anaylze relevant graphs.

**Comment by VanessaQi** [comment]
Met with Monroe on Sep 13th ---waiting for update of software

**Comment by VanessaQi** [comment]
@monroews We calibrated our spectrophotometer and tried to measure the transmittance for HA solution w/ known concentration, but the transmittance goes above 100 and we expected that to be below 100. We also tried the red dye but it also gave us above 100 transmittance(even more than HA solution)...not sure what happened

**Comment by monroews** [comment]
I found the problem. It occurred to me last night that perhaps the flow cell for the AccuVIEW meter wasn't the correct one and that is why it didn't fit properly. So I went and checked the other new turbidimeter that we had and voila, it had the flow cell for the AccuVIEW.  I calibrated it and then put in some humic acid and it responded correctly.

**Comment by VanessaQi** [comment]
@monroews I also have another question: are we actually using certain wavelength for the spectrophotometer(AccuVIEW meter)? and can we get absorbance graph for the whole wavelength range?

**Comment by monroews** [comment]
I understand that the AccuVIEW uses absorbance at 254 nm.
It does not measure absorbance at other wavelengths.

**Comment by VanessaQi** [comment]
@monroews I was thinking how should we subtract the absorbance of clay out....can we convert the effluent disturbance to absorbance and consider that absorbance as clay absorbance only?

**Comment by monroews** [comment]
You will connect the effluent turbidimeter and the AccuVIEW meter in series and pump different suspensions of clay through them.
THen you will pump different concentrations of humic acid through both meters.
From those two sets of data you can come up with the equations describing the meter readings as a function of actual concentrations of the two components (clay and humic acid). Then you will try a mixture and see if you can calculate the concentrations of the two components based on the readings from the two instruments. Note that turbidity should be a pretty good measurement regardless of the humic acid concentration. Hopefully it will work given that you have two measurements and two unknowns. The challenge could be that humic acid might adsorb to the clay and that could make it more complicated.

**Comment by mlee1721** [comment]
Used old spectrophotometer in design lab to test humic acid absorbance.  Obtained reasonable results - linear relationship, follows Beer's Law.  Shows that new spectrophotometer is faulty (machine error, not calibration or human error).  Plot below shows the data collected.

![image](https://user-images.githubusercontent.com/43385922/49104626-6d4d0300-f24c-11e8-8410-1cddee7330dd.png)

**Comment by monroews** [comment]
Provide some context. Show the data from both instruments. Include a legend in the graph.
