### ISSUE TITLE
Spectrophotometer Test-Clay +Water (Oct.1-Oct.15)

### ISSUE THREAD

**Issue by VanessaQi** [AguaClara/humic_acid#28]
Continue to test clay+water and  compare the graphical differences between HA+water and clay+water

**Comment by Carolynwamg** [comment]
Found linear relationship between clay turbidity and absorbance. The relationship was obtained: y = 0.0199x + 0.0554 . By measuring the turbidity of clay in an effluent stream, the clay's absorbance can be calculated from the relationship derived in the graph. This value can then be subtracted from the overall absorbance to find the absorbance of humic acid. 
<img width="464" alt="screen shot 2018-11-27 at 2 00 57 pm" src="https://user-images.githubusercontent.com/43160430/49104813-fe23de80-f24c-11e8-9611-d49812c1167a.png">

**Comment by VanessaQi** [comment]
We only ran experiments for clay influent w/ different turbidities and measured the corresponding absorbances.  The linear relationship helps us approximate clay absorbance based on turbidity.

**Comment by mlee1721** [comment]
We used the old experimental apparatus.  Water was pumped through the system with water pump.  Clay concentrations added through clay pump (used feedback control system ProCoDA to maintain desired clay concentration).  System then fed through floc tube into spectrophotometer and effluent turbidity meter
