### ISSUE TITLE
Test HA concentration in effluent at certain time as coag dosage changes (Oct 29th- Nov 12th) 

### ISSUE THREAD

**Issue by VanessaQi** [AguaClara/humic_acid#30]

**Comment by VanessaQi** [comment]
Chose coag dosage from 0.5 -2.5 mg/L and measured the effluent absorbances and turbidity. The turbidity should be mainly contributed by clay particles and absorbances should be mainly contributed by humic acid based on previous experimental results

**Comment by Carolynwamg** [comment]
At 0.5 mg/L, very small floc blanket formed, turbidity was 14 NTU

**Comment by VanessaQi** [comment]
After we also got results for other coag dosages, we talked w/ Monroe and think we may need to change our experimental methods
