### ISSUE TITLE
Accuview Spectrophotometer Test (Oct.15-Oct.29)

### ISSUE THREAD

**Issue by VanessaQi** [AguaClara/humic_acid#33]

**Comment by mlee1721** [comment]
Found issue with Accuview Spectrophotometer: wrong vial was being used for machine.  Recalibrated absorbance using DI water.  Absorbance larger than 0, which was good.  Tested absorbances of various humic acid samples: 5 mg/L, 10 mg/L, 15 mg/L.  Data again was plotted, shown below.

![image](https://user-images.githubusercontent.com/43385922/49105175-f0bb2400-f24d-11e8-8aca-bae1b2a61add.png)

**Comment by mlee1721** [comment]
Measured turbidity of humic acid stream was very low ; suggests that humic acid turbidity may be negligible in overall stream (when mixed with other inputs like clay).

**Comment by VanessaQi** [comment]
Beer's law is obeyed ---consistent w/ experimental results obtained from the design lab
