### ISSUE TITLE
Test HA concentration in Recycling Experiment (Nov 12th -Nov 26th)

### ISSUE THREAD

**Issue by Carolynwamg** [AguaClara/humic_acid#35]
After cleaning out residuals in original tubes, reconnect tubing to form recycled process. 
Fill bucket with 4L of water. Run through the system.
Use pipette to add increments of known concentration of HA in system and change the concentration of HA in the entire system (5mg/L, 10mg/L. 15mg/L)

**Comment by mlee1721** [comment]
Make sure increments are very small so overall volume of liquid (4L) stays roughly the same.  Allow humic acid stream to recycle for roughly an an hour (or until steady state is reached).  Record the absorbance reading of the stream from Accuview spectrophotometer.

**Comment by mlee1721** [comment]
Then perform clay experiments:

Clean system out fully (no liquid in tubing either).  Fill clean, dry bucket with 4L of water.  Run through system.  Add clay increments of known clay NTU (turbidity) into system.  Repeat procedure created above to measure absorbances of varying clay turbidities.
